name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"] 

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch

      - name: Style check with black + isort
        run: hatch run test:style

      - name: Run unit-tests
        run: hatch run test:unit

      - name: Build documentation
        run: hatch run docs:build
        if: ${{ (matrix.python-version == '3.10') && (matrix.os == 'ubuntu-latest')}}
